version: "3"

services:

  grafana:
    image: grafana/grafana:latest
    volumes:
      - /dev/log:/dev/log
      - ${PWD}/etc_grafana_provisioning:/etc/grafana/provisioning
      - ${PWD}/var_lib_grafana:/var/lib/grafana/
      - ${PWD}/usr_share_grafana_public_img:/usr/share/grafana/public/img/weka
    restart: always
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:2.3.0
    volumes:
      - /dev/log:/dev/log
      - ${PWD}/etc_loki:/etc/loki
      - ${PWD}/loki_data:/loki
    command: -config.file=/etc/loki/loki-config.yaml
    restart: always
    ports:
      - "3100:3100"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - /dev/log:/dev/log
      - /etc/hosts:/etc/hosts
      - ${PWD}/etc_prometheus:/etc/prometheus
      - ${PWD}/prometheus_data:/prometheus
    command: --storage.tsdb.retention.size=20GB --config.file=/etc/prometheus/prometheus.yml
    restart: always
    ports:
      - "9090:9090"

  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - /dev/log:/dev/log
      - ${PWD}/etc_alertmanager:/etc/alertmanager
    command: --config.file="/etc/alertmanager/alertmanager.yml" --log.level=debug # -web.external-url=http://hostname-here:9093/
    #restart: always
    ports:
      - "9093:9093"

  export:
    image: wekasolutions/export:latest
    volumes:
      - /dev/log:/dev/log
      - ${HOME}/.weka:/weka/.weka
      - /etc/hosts:/etc/hosts
      - ${PWD}/export.yml:/weka/export.yml
    command: -v
    restart: always
    ports:
      - "8001:8001"

  quota-export:
    image: wekasolutions/quota-export:latest
    volumes:
      - /dev/log:/dev/log
      - ${HOME}/.weka:/weka/.weka
      - /etc/hosts:/etc/hosts
      - ${PWD}/quota-export.yml:/weka/quota-export.yml
    restart: always
    ports:
      - "8101:8101"
